# project-info
name: adult-base


# dir
# dir
data_dir: ./dataset/cifar10/
#resume: ''
# resume: ./model/cifar10/v6/best.pth.tar
# 从V3开始，正式进入论文的实验阶段
save: ./model/cifar10/v6/
base_mode: ./model/cifar10/v6/best.pth.tar
decoder_mode: ./model/cifar10/v6/attack-model/nothing.pth.tar
#origin_data_output: /data/yangjirui/vfl-tab-reconstruction/rebuild-data/adult/v1/origin_data.csv
#rebuild_data_output: /data/yangjirui/vfl-tab-reconstruction/rebuild-data/adult/v1/rebuild_data.csv

# model
report_freq: 10
workers: 0


# Hyperparameters
lr: 0.1
momentum: 0.9
weight_decay: 3e-5
gamma: 0.97
epochs: 120
batch_size: 64

# 重建超参数
NIters: 1000
Ndata: 10
bloss: 0
bloss2: 10
bloss2_v2: 0
numloss: 1

iloss: 0
nloss: 0
norloss: 0


