# project-info
name: adult-base


# dir
data_dir: ./dataset/credit/clients.xls
#resume: ''
#resume: ./model/adult/v0/best.pth.tar
#save: ''
save: ./rebuild-data/credit/v6/
base_mode: ./model/credit/v6/best.pth.tar
decoder_mode: ./model/credit/v6/attack-model/data_decoder120+.pth.tar
#origin_data_output: ./rebuild-data/adult/v1/origin_data.csv
#rebuild_data_output: ./rebuild-data/adult/v1/rebuild_data.csv
shadow_model: ./model/credit/v6/attack-model/data_shadow_model120+.pth.tar

# model
report_freq: 10
workers: 0


# Hyperparameters
lr: 0.001
momentum: 0.9
weight_decay: 3e-5
gamma: 0.97
epochs: 120
batch_size: 64

# 重建超参数
NIters: 1000
Ndata: 10
bloss: 0
bloss2: 1
bloss2_v2: 0
numloss: 0.1

iloss: 0
nloss: 0
norloss: 0


