# project-info
name: adult-base


# dir
data_dir: ./dataset/adult/adult.data
#resume: ''
# /home/yangjirui/data/VFL/vfl-data-reconstuction/PR/vfl-data-reconstruction/model/adult/base/v0/best.pth.tar
resume: ./model/adult/base/v0/best.pth.tar
# 从V3开始，正式进入论文的实验阶段
save: ./model/adult/base/v0/

# model
report_freq: 10
workers: 8


# Hyperparameters
lr: 0.001
momentum: 0.9
weight_decay: 3e-5
gamma: 0.97
epochs: 120
batch_size: 64

