# project-info
name: cifar10-base


# dir
data_dir: ./dataset/cifar10/
#resume: ''
resume: ./model/cifar10/base/v0/best.pth.tar
# 从V3开始，正式进入论文的实验阶段
save: ./model/cifar10/base/v0/

# model
report_freq: 10
workers: 32


# Hyperparameters
lr: 0.02
# momentum: 0.9
# weight_decay: 3e-5
# gamma: 0.97
alpha: 0.05
eps: 1.0
epochs: 100
batch_size: 64

